---
- hosts: ws
  become: yes
  become_user: root
  ignore_errors: yes
  tasks:
     - name: Install Packages
       yum:
         state: present
         name:
           - docker
           - wget
           - lsof
           - passwd 
           - unzip 
           - java-11*
     - name: Create Directoty 
       file: 
         path: /opt/qa/spg
         state: directory
     - name: Create Log file
       file:
         path: /opt/qa/spg/spg.log
         state: touch     
     - name: Start and enable Daemon 
       system_service:
          name: docker
          state: started
          enables: yes 